api/urls.py
from django.urls import path
from .views import MenuPage, ApiPage, WordViewSet, WordAPIView


app_name = 'doc'
urlpatterns = [
    path('', MenuPage.as_view(), name='menu'),
    path('api/', ApiPage.as_view(), name=''),
    path('api/list/', WordViewSet.as_view({'get': 'own_list'}), name='api'),
    # path('api/create/', WordViewSet.as_view({'get': 'create_word'}), name='api'),
    # path('api/list/', WordAPIView.as_view(), name='api'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('dictionary/', include('dictionary.urls')),
    path('doc/', include('api.urls', namespace='doc')),
]

api/views.py
from django.http import QueryDict
from django.shortcuts import render
from django import views
from dictionary.models import Word
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import (
    serializers,
    viewsets,
    permissions,
    response,
    request,
    authentication,
)
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer

class WordSerializer(serializers.ModelSerializer):
    class Meta:
        model = Word
        fields = \
            ('english', 'transcription', 'translation', \
            'note', 'favourite', 'category')


class MenuPage(views.View):
    def get(self, request):
        return render(request, 'api/doc_home.html')


class ApiPage(views.View):
    def get(self, request):
        return render(request, 'api/get_api.html')


class WordViewSet(LoginRequiredMixin, viewsets.ViewSet):
    renderer_classes = [JSONRenderer]

    def own_list(self, request):
        return response.Response(
                WordSerializer(Word.objects.filter(
                        user=request.user), many=True).data
            )

    # def create_word(self, request):
    #     print(request.data)
    #     serializer = WordSerializer(request.data)

# Thats not working, or i am stupid
class WordAPIView(APIView):
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]
    renderer_classes = [JSONRenderer]

    def get(self, request):
        return response.Response(WordSerializer(
            Word.objects.filter(user=self.request.user)).data
            )

api/templates/api/doc_home.html
{% extends "base.html" %}

{% block style %}
<style>
    .o_btn {
        margin-top: 1%;
        height: 60px;
        text-align: center;
        padding-top: 15px;
        width: 94%;
        margin-left: 3%;
    }
</style>
{% endblock style %}

{% block content %}
<div style="width: 600px; height: 500px; margin-left: 30%;" class="card bg-light">
    <div class="card-header bg-dark text-light"
        style="text-align: center; height: 60px; padding-top: 2%; font-weight: bold;">
        <div class="card-text">Click to get info about something</div>
    </div>
    <div class="btn btn-success o_btn">How to use this site</div>
    <div class="btn btn-info o_btn">How does this site work</div>
    <a href="{% url 'doc:api' %}">Api</a>
</div>
{% endblock content %}

api/templates/api/get_api.html
{% extends "base.html" %}

{% block content %}
<h1>Abcde</h1>
{% endblock content %}