api/urls.py
from django.urls import path
from .views import MenuPage, ApiPage, WordViewSet, WordAPIView


app_name = 'doc'
urlpatterns = [
    path('', MenuPage.as_view(), name='menu'),
    path('api/', ApiPage.as_view(), name=''),
    path('api/list/', WordViewSet.as_view({'get': 'own_list'}), name='api'),
    # path('api/create/', WordViewSet.as_view({'get': 'create_word'}), name='api'),
    # path('api/list/', WordAPIView.as_view(), name='api'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('dictionary/', include('dictionary.urls')),
    path('doc/', include('api.urls', namespace='doc')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
</head>
<body>
    <!-- https://www.geeksforgeeks.org/how-to-animate-a-progress-bar-in-bootstrap/ -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="height: 70px;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">English dictionary</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div style="margin-left: 18%;" class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <ul class="navbar-nav justify-content-center">
              <li class="nav-item">
                <a class="nav-link"
                    aria-current="page" href="{% url 'dict-list' %}">
                    Dictionary</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'run' %}">Run</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Leaderboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'doc:menu' %}">Documentation</a>
              </li>
            </ul>
          </div>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li style="margin-top: 8px; margin-right: 10px;" class="nav-item text-light">
                    Hello, <strong>{{ request.user }}</strong>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
              </ul>
          </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    {% block script %}
    {% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>